name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

env:
  DOTNET_VERSION: "net10.0"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
  DOTNET_MULTILEVEL_LOOKUP: 0
  PROJECT: "Bezalu.ProjectReporting.Web"
  BUILD_CONFIG: "Release"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and deploy Bezalu.ProjectReporting.Web
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.PROJECT }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          submodules: true
          lfs: false

      - name: 'Set up .NET version: ${{ env.DOTNET_VERSION }}'
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Workload Restore
        run: dotnet workload restore

      - name: 'Build and prepare .NET project for deployment'
        run: dotnet publish -configuration Release -output ./publish

      - name: Deploy ${{ env.PROJECT }} to Azure Static Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish/wwwroot"
          api_location: ""
          output_location: "publish/wwwroot"
          skip_api_build: true
          skip_app_build: true
          production_branch: 'main'

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
